[package]
name = "tedge_signal_ext"
description = "thin-edge extension adding unix signal handling"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
signal-hook = { workspace = true }
tedge_actors = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[target.'cfg(unix)'.dependencies]
signal-hook-tokio = { workspace = true }

[lints]
workspace = true
