version: '3'
services:
  bootstrap:
    user: root
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    entrypoint:
      - sh
    command:
      - -c
      # - sleep infinity
      - init.sh bootstrap
    volumes:
      - tedge_logs:/var/log/tedge
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins
  
  mqtt-broker:
    build:
      dockerfile: ./images/mosquitto.dockerfile
      context: ../..
    # Optional: Expose port if you would like the mqtt broker to be available for
    # components outside of this docker-compose. It is not required for communication within network
    # ports:
    #   - 1883:1883
    restart: always
    env_file:
      - .env
      # bootstrapping secrets is optional
      # If it is not provided then you will have to bootstrap it
      # using the instructions printed on the console!
      - .env.secrets
    environment:
      - SERVICE_NAME=mqtt-broker
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
      - TEDGE_MQTT__BIND_ADDRESS=0.0.0.0
      - TEDGE_MQTT__PORT=1883

    volumes:
      - bootstrap:/bootstrap
      - tedge_cert:/device-certs
      - tedge_broker:/etc/tedge
      - tedge_logs:/var/log/tedge
    networks:
      - tedge
    depends_on:
      bootstrap:
        condition: service_completed_successfully

  tedge-mapper-c8y:
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    command:
      - tedge-mapper-c8y
      - c8y
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins
    depends_on:
      mqtt-broker:
        condition: service_healthy
      # tedge-agent:
      #   condition: service_started
      # c8y-configuration-plugin:
      #   condition: service_healthy

    restart: always
    links:
      - "mqtt-broker:mqtt"
    networks:
      - tedge
  
  tedge-agent:
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    command:
      - tedge-agent
    restart: always
    # Optional: Expose port if you would like the tedgeapi endpoint to be available for
    # components outside of this docker-compose. It is not required for communication within network
    # ports:
    #   - 8000:80
    # FIXME: tedge-agent requires c8y.url to be set?
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
      # FIXME: Separate the HTTP bind setting with the mqtt setting
      - TEDGE_MQTT__BIND_ADDRESS=0.0.0.0
      - TEDGE_HTTP__PORT=80
    volumes:
      - tedge_cert:/device-certs
      - tedge_cache:/var/tedge
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins

    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
    networks:
      - tedge

  c8y-configuration-plugin:
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    restart: always
    command:
      - c8y-configuration-plugin
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"
    networks:
      - tedge

  c8y-log-plugin:
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    command:
      - c8y-log-plugin
    restart: always
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"

    networks:
      - tedge
  
  c8y-firmware-plugin:
    build:
      dockerfile: ./images/tedge-component.alpine.dockerfile
      context: ../..
    command:
      - c8y-firmware-plugin
    restart: always
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      # - tedge_data:/etc/tedge
      - tedge_c8y:/etc/tedge/c8y
      - tedge_operations:/etc/tedge/operations
      - tedge_device:/etc/tedge/device
      - tedge_plugins:/etc/tedge/plugins
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"
    networks:
      - tedge

networks:
  tedge:

volumes:
  bootstrap:
  tedge_broker:
  tedge_cert:
  tedge_logs:
  tedge_cache:

  # TODO: Individual volume mounts don't seem to work
  # though this will be solved by API based plugin discovery
  # /etc/tedge sub folders
  # tedge_data:
  tedge_operations:
  tedge_c8y:
  tedge_device:
  tedge_plugins:
