#!/bin/sh
set -e

# Automatically added by thin-edge.io
ACTION=
case "$0" in
    *.*-install) ACTION=install; ;;
esac

if [ "$ACTION" = install ]; then
    if command -v tedgectl >/dev/null 2>&1; then
        tedgectl enable c8y-remote-access-plugin.socket >/dev/null || true
    fi
fi
# End automatically added section
# Automatically added by thin-edge.io
if command -v tedgectl >/dev/null 2>&1; then
    tedgectl start c8y-remote-access-plugin.socket >/dev/null || true
fi
# End automatically added section

### Create supported operation files
c8y-remote-access-plugin --init
