Port 22222
ListenAddress 127.0.0.1

AuthorizedKeysFile /etc/ssh/authorized-keys/%u

AllowTcpForwarding no
Match Group root
AllowTcpForwarding yes

PubkeyAuthentication yes
#PasswordAuthentication no
#PermitRootLogin no
