#!/bin/sh
set -e

# cargo-deb helpers
cargodeb_prepare_service() {
    service_file="$2"
    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        if deb-systemd-helper debian-installed "$service_file"; then
            # This will only remove masks created by d-s-h on package removal.
            deb-systemd-helper unmask "$service_file" >/dev/null || true

            if deb-systemd-helper --quiet was-enabled "$service_file"; then
                # Create new symlinks, if any.
                deb-systemd-helper enable "$service_file" >/dev/null || true
            fi
        fi

        # Update the statefile to add new symlinks (if any), which need to be cleaned
        # up on purge. Also remove old symlinks.
        deb-systemd-helper update-state "$service_file" >/dev/null || true
    fi
}

cargodeb_prepare_service "$1" tedge-mapper-aws.service
cargodeb_prepare_service "$1" tedge-mapper-az.service
cargodeb_prepare_service "$1" tedge-mapper-c8y.service
cargodeb_prepare_service "$1" tedge-mapper-collectd.service

# Automatically added by cargo-deb
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			deb-systemd-invoke try-restart tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service >/dev/null || true
		fi
	fi
fi
# End automatically added section

enable_start_service() {
    name="$1"

    if command -v deb-systemd-helper >/dev/null 2>&1; then
        deb-systemd-helper enable "$name" >/dev/null || true
    else
        systemctl enable "$name" >/dev/null || true
    fi

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true

        if command -v deb-systemd-invoke >/dev/null 2>&1; then
            deb-systemd-invoke start "$name" >/dev/null || true
        else
            systemctl start "$name" >/dev/null || true
        fi
    fi
}

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the service if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        enable_start_service tedge-mapper-c8y.service
    fi
    ### Enable the service if the device is connected to az cloud
    if [ -f "/etc/tedge/mosquitto-conf/az-bridge.conf" ]; then
        enable_start_service tedge-mapper-az.service
    fi
    ### Enable the service if the device is connected to aws cloud
    if [ -f "/etc/tedge/mosquitto-conf/aws-bridge.conf" ]; then
        enable_start_service tedge-mapper-aws.service
    fi
    if [ -d /run/systemd/system ]; then
        ### Enable the service if the collectd is running on the device
        if systemctl is-active --quiet collectd.service; then
            enable_start_service tedge-mapper-collectd.service
        fi
    fi
fi

if [ -f /var/lib/dpkg/info/tedge_mapper.postrm ]; then
    # Prevent purge from deleting files related to the package
    rm -f /var/lib/dpkg/info/tedge_mapper.postrm
fi
