#!/bin/sh

set -e

# Stop the services only if systemctl is available
if [ -d /run/systemd/system ]; then
    if command -v deb-systemd-invoke >/dev/null 2>&1; then
        deb-systemd-invoke stop tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service >/dev/null || true
    elif command -v systemctl >/dev/null 2>&1; then
        systemctl stop tedge-mapper-c8y.service >/dev/null || true
        systemctl stop tedge-mapper-collectd.service >/dev/null || true
        systemctl stop tedge-mapper-az.service >/dev/null || true
        systemctl stop tedge-mapper-aws.service >/dev/null || true
    fi
fi
