#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
    if command -v deb-systemd-invoke >/dev/null 2>&1; then
	    deb-systemd-invoke stop c8y-configuration-plugin.service >/dev/null || true
    elif command -v systemctl >/dev/null 2>&1; then
        if systemctl is-active --quiet c8y-configuration-plugin.service; then
            systemctl stop c8y-configuration-plugin.service
        fi
    fi
fi
