#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    if command -v deb-systemd-invoke >/dev/null 2>&1; then
	    deb-systemd-invoke stop tedge-watchdog.service >/dev/null || true
    elif command -v systemctl >/dev/null 2>&1; then
        systemctl stop tedge-watchdog.service
    fi
fi
