version: '3'
services:
  
  mqtt-broker:
    image: reubenmiller/tedge-mosquitto:2.0.14
    # Optional: Expose port if you would like the mqtt broker to be available for
    # components outside of this docker-compose. It is not required for communication within network
    # ports:
    #   - 1883:1883
    restart: always
    env_file:
      - .env
      # bootstrapping secrets is optional
      # If it is not provided then you will have to bootstrap it
      # using the instructions printed on the console!
      - .env.secrets
    environment:
      - SERVICE_NAME=mqtt-broker
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
      - TEDGE_MQTT__BIND_ADDRESS=0.0.0.0
      - TEDGE_MQTT__PORT=1883

    volumes:
      - bootstrap:/bootstrap
      - tedge_cert:/device-certs
      - tedge_broker:/etc/tedge
      - tedge_logs:/var/log/tedge
    networks:
      - tedge

  tedge-mapper-c8y:
    image: reubenmiller/tedge-component:alpine
    command:
      - tedge-mapper-c8y
      - c8y
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      - tedge_data:/etc/tedge
    depends_on:
      mqtt-broker:
        condition: service_healthy
    restart: always
    links:
      - "mqtt-broker:mqtt"
    networks:
      - tedge

  tedge-agent:
    image: reubenmiller/tedge-component:alpine-docker
    command:
      - tedge-agent
    restart: always
    # Optional: Expose port if you would like the tedgeapi endpoint to be available for
    # components outside of this docker-compose. It is not required for communication within network
    # ports:
    #   - 8000:8000
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
      # FIXME: Separate the HTTP bind setting with the mqtt setting
      - TEDGE_MQTT__BIND_ADDRESS=0.0.0.0
      - TEDGE_HTTP__PORT=80
    volumes:
      - tedge_cert:/device-certs
      - tedge_cache:/var/tedge
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      - tedge_data:/etc/tedge
      - container_groups:/var/tedge-container-plugin

      # Enable docker from docker - But then this container has elevated access to system resources!
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
    networks:
      - tedge

  c8y-configuration-plugin:
    image: reubenmiller/tedge-component:alpine
    restart: always
    command:
      - c8y-configuration-plugin
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      - tedge_data:/etc/tedge
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"
    networks:
      - tedge

  c8y-log-plugin:
    image: reubenmiller/tedge-component:alpine
    command:
      - c8y-log-plugin
    restart: always
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      - tedge_data:/etc/tedge
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"
    networks:
      - tedge

  c8y-firmware-plugin:
    image: reubenmiller/tedge-component:alpine
    command:
      - c8y-firmware-plugin
    restart: always
    environment:
      - TEDGE_MQTT__CLIENT_HOST=mqtt
      - TEDGE_DEVICE__CERT_PATH=/device-certs/tedge-certificate.pem
    env_file:
      - .env
    volumes:
      - tedge_cert:/device-certs
      - tedge_logs:/var/log/tedge
      # Optional (only required to share operations and config)
      - tedge_data:/etc/tedge
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
      - "tedge-agent:tedgeapi"
    networks:
      - tedge

  container-monitor:
    image: reubenmiller/community-container-monitor:latest
    restart: always
    env_file:
      - .env
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - LOG_LEVEL=debug
      - INTERVAL=60
      # It seems that telemetry does not work when doing docker-from-docker?
      - TELEMETRY=1
    volumes:
      # FIXME: Remove once there is an api to get the container info
      - tedge_data:/etc/tedge
      # Enable docker monitor (read only access to socket)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      mqtt-broker:
        condition: service_healthy
    links:
      - "mqtt-broker:mqtt"
    networks:
      - tedge

networks:
  tedge:

volumes:
  bootstrap:
  tedge_broker:
  tedge_cert:
  tedge_logs:
  tedge_cache:
  tedge_data:
  container_groups:
