#!/bin/sh
set -e

purge_mapper_lock() {
    rm -f /run/lock/tedge-mapper-c8y.lock
    rm -f /run/lock/tedge-mapper-az.lock
    rm -f /run/lock/tedge-mapper-aws.lock
    rm -f /run/lock/tedge-mapper-collectd.lock
}

case "$1" in
    purge)
        purge_mapper_lock
    ;;
esac



