#!/bin/sh
set -e

# Deprecate: Remove line in 1.x release
# Prevent purge from deleting files related to the package
rm -f /var/lib/dpkg/info/tedge_agent.postrm

# Remove older prerm maintainer scripts which would stop the tedge-agent service during an OTA
rm -f /var/lib/dpkg/info/tedge_agent.prerm

# Automatically added by thin-edge.io
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	name="tedge-agent.service"
	/etc/init.d/"${name%.*}" enable ||:
fi
# End automatically added section
